#
server:
    port: 8081
mybatis:
        config-locations: classpath:mapping/confg.xml
        mapper-locations: classpath:mapping/mapper/*.xml
        type-aliases-package: com.jk.model
spring:
    datasource:
        driver-class-name: com.mysql.jdbc.Driver
        password: 666
        url: jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=utf-8&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
        username: root
    thymeleaf:
        cache: false
        prefix: classpath:/templates/
        suffix: .html
